name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install npm dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          touch .env
          echo "API_URL=${{ env.API_URL }}" >> .env

      - name: Build release
        run: ./gradlew assembleRelease
        working-directory: android


      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}      
          groups: testers
          file: android/app/build/outputs/apk/release/app-release.apk
