name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: install npm dependencies
        run: npm install

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: create .env file
        run: |
          touch .env
          echo "API_URL=${{ env.API_URL }}" >> .env

      - name: build release
        run: ./gradlew assembleDebug
        working-directory: android

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}      
          groups: testers
          file: android/app/build/outputs/apk/debug/app-debug.apk
